#ifndef KIVO_APP_VERSION_H
#define KIVO_APP_VERSION_H

#define KIVO_PRODUCT_NAME "KIVO ONE V1"
#define KIVO_FIRMWARE_VERSION "0.1.0-i1"
#define KIVO_FIRMWARE_ITERATION "Iteration 1"
#define KIVO_BUILD_TARGET "ESP32-S3"

#endif /* KIVO_APP_VERSION_H */